seed: 0
num_envs: 512
board_size: 15
device: cuda
out_device: cpu
run_dir:

augment: false

epochs: 1000
steps: 128
save_interval: 300
survival_reward: 0.001

collector_type: "BlackPlay"

train_checkpoint:

opponent:
  type: random # "random" | "pretrained"
  checkpoint:
  algo_name: ${algo.name}
  algo_cfg: ${baseline}

wandb:
  group: ${board_size}_${board_size}_${algo.name}_InRL
  project: gomoku_rl
  mode: online # set to 'disabled' when debugging locally

defaults:
  - _self_
  - algo: ppo
  - baseline: ppo
